### ISSUE TITLE
Error when using "budgie init <name>"

### ISSUE THREAD

**Issue by nathan-a-macleod** [lugocorp/budgie#1]
In the README file of budgie, under "Create a project", it says to use the following command:
`budgie init <name>`
However for some reason, when I run the following command:
`budgie init MyFirstProject`
It gives the following error: (the previous command mentioned in the README file has no errors when run)
`/usr/local/bin/budgie: line 1: syntax error near unexpected token '('`
`/usr/local/bin/budgie: line 1: const mime=require("mime-types");`
The same error also happens when I do:
`budgie build`
and
`budgie open`

**Comment by alugocp** [comment]
How did you install the tool? I might have an issue in my package.json

**Comment by alugocp** [comment]
Wait jk I found the issue. Go ahead and reinstall it

**Comment by nathan-a-macleod** [comment]
Yep that works now :)
