### ISSUE TITLE
Issue when using "budgie open"

### ISSUE THREAD

**Issue by nathan-a-macleod** [lugocorp/budgie#3]
There seems to be an issue when I run `budgie open`. Running the command doesn't actually give me any issues, however, when the browser page opens up, these errors are displayed in the console:
![Screenshot 2021-04-07 10 23 00 AM](https://user-images.githubusercontent.com/64553342/113843154-42afd500-978b-11eb-8f19-a3598fd3defa.png)

I believe it is something to do with the `~/budgie/<project_name>/index.html` file - it links to the files in this way:
`<script src="/usr/local/lib/node_modules/budgiejs/lib/arcade.js">`

However I think it must be something to do with my computer, because `/usr/local/lib/node_modules/budgiejs/lib/arcade.js` **does** seem to be an actual, existing file... strange.

**Comment by nathan-a-macleod** [comment]
Actually I think I know what the problem is - I'll do a pull request in a second...

**Comment by nathan-a-macleod** [comment]
So I'm not entirely sure how to fix this in code, but in the `~/budgie/<project_name>/index.html` file, if you change where it says for example:
`<script src="/usr/local/lib/node_modules/budgiejs/lib/arcade.js">` 
to, in this case:
`<script src="../lib/arcade.js">` 
it seems to work for me.

Obviously, that would be annoying for developers to manually have to change the index.html file all the time, so here must be a way to change that as it is creating the `index.html` file.

**Comment by alugocp** [comment]
I actually did have `<script src="../lib/arcade.js">` in an earlier version of the code, when every Budgie project had the library code copied into it. However I changed it to keep Budgie projects looking cleaner.
Are you creating projects from within the budgie directory that you cloned from here? It seems you also globally installed the library from npm, which is good. I'm not sure why it would say the file doesn't exist though...I'll take a look at it after work today.

**Comment by nathan-a-macleod** [comment]
Yep - I'm in the directory: `/home/<my_username>/budgie/`, and running the commands `budgie init <project_name>`, etc.

**Comment by alugocp** [comment]
Okay cool. You don't actually have to do that, since you installed it globally with npm you can just create Budgie projects wherever in your filesystem. But I don't imagine that would help your issue here

**Comment by alugocp** [comment]
If I had to guess, I'd say your browser doesn't like using absolute paths with the file:// protocol. Are you by any chance using Chrome? You could try `budgie package` and then `budgie open` to remove all external JS dependencies.

**Comment by nathan-a-macleod** [comment]
Ah yes, that works now!
I'm using Google Chrome and Linux. I believe `file://<folder>/<folder>/` is for windows, and `/<folder>/<folder>/` etc is for linux - which could be why.

**Comment by alugocp** [comment]
Okay I just merged the build and package commands to remove dependence on absolute filepaths, so I'm gonna close this. Thanks so much for bringing this up!
